/**
 * MEDTRIX CORE ENGINE v2.3 (Auto-Fix Edition)
 * Handles API Keys, Database, and auto-converts file lists to readable titles.
 */

const MEDTRIX = {
    config: {
        version: '2.3',
        // Split Key to bypass GitHub Security
        kPart1: "AIzaSyAvG61ZVSmjer_",
        kPart2: "PNsixRsxxqf7gaoNz7nQ",
        themeKey: 'medtrix-theme',
        dbKey: 'medtrix_analytics'
    },

    data: {
        _manifestCache: null,
        _fileCache: {},

        // INTELLIGENT MANIFEST LOADER
        getManifest: async function() {
            if (this._manifestCache) return this._manifestCache;
            
            try {
                // 1. Try loading the file generated by Python script
                const res = await fetch('quiz_manifest.json');
                if (!res.ok) throw new Error("quiz_manifest.json not found");
                
                let rawList = await res.json();
                
                // 2. AUTO-FIX: Convert simple string list ["file.json"] to Object list
                if (Array.isArray(rawList) && typeof rawList[0] === 'string') {
                    console.log("Converting simple file list to rich metadata...");
                    return rawList.map(filename => {
                        // Guess Category from filename
                        let cat = "General";
                        const lower = filename.toLowerCase();
                        if (lower.includes('neuro')) cat = "Neurology";
                        else if (lower.includes('cardio')) cat = "Cardiology";
                        else if (lower.includes('surg')) cat = "Surgery";
                        else if (lower.includes('obg') || lower.includes('gyn')) cat = "Obstetrics & Gynaecology";
                        else if (lower.includes('pedia')) cat = "Pediatrics";
                        else if (lower.includes('derma')) cat = "Dermatology";
                        else if (lower.includes('ent')) cat = "ENT";
                        else if (lower.includes('anat')) cat = "Anatomy";
                        else if (lower.includes('physio')) cat = "Physiology";
                        
                        return {
                            title: this.formatTitle(filename),
                            file: filename,
                            category: cat,
                            questions: "?" // Placeholder until opened
                        };
                    });
                }
                
                this._manifestCache = rawList;
                return rawList;
            } catch (e) {
                console.error("Manifest Error:", e);
                // Return empty array so page doesn't crash
                return [];
            }
        },

        getQuiz: async function(filename) {
            if (this._fileCache[filename]) return this._fileCache[filename];
            try {
                const res = await fetch(`quiz_data/${filename}`);
                const data = await res.json();
                
                // AUTO-FIX: Sanitize data structure errors
                if(data.questions) {
                    data.questions = data.questions.map(q => {
                        // Ensure Text is string
                        if(typeof q.question === 'object') q.text = q.question.text || JSON.stringify(q.question);
                        else q.text = q.question || q.text;

                        // Ensure Options are standard
                        if(q.options) {
                            if(!Array.isArray(q.options)) q.options = Object.values(q.options);
                            q.options = q.options.map(opt => {
                                if(typeof opt === 'object') return { text: opt.text || opt.value || "Option", correct: opt.correct || false };
                                return { text: opt, correct: false };
                            });
                        }
                        return q;
                    });
                }
                this._fileCache[filename] = data;
                return data;
            } catch (e) { return null; }
        },

        formatTitle: function(rawName) {
            if(!rawName) return "Untitled Test";
            let clean = rawName.replace('.json', '').replace(/_/g, ' ').replace(/-/g, ' ');
            
            const dict = { 
                'obg': 'Obstetrics', 
                'psm': 'Community Medicine', 
                'ent': 'ENT', 
                'pyq': 'Previous Year Qs',
                'fmt': 'Forensic Medicine',
                'inicet': 'INICET', 
                'neet': 'NEET PG',
                'fmge': 'FMGE',
                'uw': 'UWorld'
            };
            
            return clean.split(' ').map(w => dict[w.toLowerCase()] || (w.charAt(0).toUpperCase() + w.slice(1))).join(' ');
        }
    },

    db: {
        saveResult: function(qData, isCorrect, filename) {
            let history = JSON.parse(localStorage.getItem(MEDTRIX.config.dbKey) || '[]');
            history = history.filter(h => h.uid !== qData.uid);
            history.push({
                uid: qData.uid,
                text: qData.text,
                explanation: qData.explanation,
                timestamp: Date.now(),
                isCorrect: isCorrect,
                source: filename,
                options: qData.options
            });
            try {
                localStorage.setItem(MEDTRIX.config.dbKey, JSON.stringify(history));
                MEDTRIX.ui.toast("Progress Saved");
            } catch(e) { console.warn("Storage Full"); }
        }
    },

    ai: {
        getKey: function() {
            const manual = localStorage.getItem('medtrix_manual_key');
            if(manual) return manual;
            return MEDTRIX.config.kPart1 + MEDTRIX.config.kPart2;
        },

        ask: async function(prompt, context) {
            const key = this.getKey();
            const finalPrompt = `Act as a medical professor. ${prompt}\n\nContext: ${context.substring(0, 800)}`;

            try {
                const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${key}`, {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ contents: [{ parts: [{ text: finalPrompt }] }] })
                });

                const data = await response.json();
                
                if (data.error) {
                    if(data.error.code === 400) {
                        const newKey = prompt("API Key Expired. Enter a new Google Gemini Key:");
                        if(newKey) localStorage.setItem('medtrix_manual_key', newKey.trim());
                    }
                    throw new Error(data.error.message);
                }
                return data.candidates[0].content.parts[0].text;
            } catch (e) {
                return `AI Error: ${e.message}`;
            }
        }
    },

    ui: {
        initTheme: function() {
            const theme = localStorage.getItem(MEDTRIX.config.themeKey) || 'light';
            document.documentElement.setAttribute('data-theme', theme);
        },
        toast: function(msg) {
            let t = document.createElement('div');
            t.innerText = msg;
            t.style.cssText = "position:fixed; bottom:90px; left:50%; transform:translateX(-50%); background:rgba(0,0,0,0.8); color:#fff; padding:8px 16px; border-radius:20px; z-index:9999; font-size:0.8rem; pointer-events:none; animation:fadeIn 0.3s;";
            document.body.appendChild(t);
            setTimeout(() => t.remove(), 2000);
        }
    }
};

MEDTRIX.ui.initTheme();